### ISSUE TITLE
beta and gamma mask base R functions

### ISSUE THREAD

**Issue by richardreeve** [boydorr/rdiversity#1]
We need to change the names of beta() and gamma() to avoid masking base R functions.

**Comment by richardreeve** [comment]
I've forked the main repository and am seeing what's necessary to replace:

- alpha(), beta(), rho(), gamma() with raw.alpha(), etc.
- alphabar(), betabar(), etc. with normalised.alpha(), etc.

**Comment by mysteryduck** [comment]
Still uncertain about the lengthy names. Also the dot will mess with the documentation. How about keeping alphabar() and adding alpharaw() instead of renaming to normalised.alpha() and raw.alpha()

**Comment by richardreeve** [comment]
How do dots mess with the docs?

**Comment by mysteryduck** [comment]
The usage section will assume you are applying normalised() or raw() on an object of class alpha. I guess you can override it, but I've tried to avoid doing that.

**Comment by richardreeve** [comment]
It doesn't seem to:
```{R}
> ?normalised.beta
Low level diversity components: normalised beta

Description

Calculates the low-level diversity component necessary for calculating normalised beta diversity.

Usage
normalised.beta(super)

Arguments
super	object of class supercommunity.
```

**Comment by richardreeve** [comment]
They may if you are specifically dealing with one of these generalised functions like plot(), but not ordinarily...

**Comment by mysteryduck** [comment]
Cool~ no worries then :)
