### ISSUE TITLE
Problem in calculating beta diversity

### ISSUE THREAD

**Issue by KatharinaKordubel** [boydorr/rdiversity#15]
Dear developers,

I have a dataset of phytoplankton abundances for which I am trying to calculate the beta diversity, usually ranging from 0 to 1.
However when I run my code the values for beta diversity are far outside of this normal range. 

Do you have any idea what could be the issue here? 

Thanks in advance for any help.

[DataGithub.txt](https://github.com/boydorr/rdiversity/files/6460630/DataGithub.txt)

`library(rdiversity)

data <- read.table("DataGithub.txt", header = T)

data.spring <- subset(data, Season == "Spring")

# Metacommunity
spring <- as.data.frame(t(data.spring[, 2:81]))
spring <- spring/sum(spring)
meta.spring <- metacommunity(spring)

b <- norm_beta(meta.spring)

## q = 0 
beta.0 <- subdiv(b, 0)  
data.spring$beta0 <- beta.0$diversity

## q = 1
SC.beta.1 <- subdiv(b, 1)  
data.spring$beta1 <- SC.beta.1$diversity

## q = 2
SC.beta.2 <- subdiv(b, 2)  
data.spring$beta2 <- SC.beta.2$diversity

# checking the values for beta
data.spring$beta0
data.spring$beta1
data.spring$beta2
`

**Comment by KatharinaKordubel** [comment]
Hello @richardreeve 

We actually tried calculating beta diversity using raw_beta() previously, but basing ourselves on a paper by Sarker et al 2019 where normalized beta diversity with values between 0 and 1 were obtained, we got confused. 

But thank you very much for your help. Your message was very clear and helped us to solve our problem.

**Comment by richardreeve** [comment]
Sorry for the delay in following this up. I think that must have been a typo in the Sarker et al. paper. Could you let me know which paper it is you are referring to?

**Comment by KatharinaKordubel** [comment]
Of course. The paper we were basing ourselves on was:  Sarker, S. K., 
Reeve, R., Paul, N. K., & Matthiopoulos, J. (2019). Modelling spatial 
biodiversity in the world?s largest mangrove ecosystem?The Bangladesh 
Sundarbans: A baseline for conservation. Diversity and Distributions, 25
(5), 729-742.





Bitte beachten Sie: Die Helmholtz-Zentrum Geesthacht - Zentrum für Material- und Küstenforschung GmbH hat sich am 31.03.2021 in Helmholtz-Zentrum hereon GmbH umbenannt. Informationen dazu finden Sie unter www.hereon.de/name <https://www.hereon.de/name>

Please note: Since the 31st of March 2021 the Helmholtz-Zentrum Geesthacht – Center for Materials and Coastal Research has a new name: Helmholtz-Zentrum hereon GmbH. More information www.hereon.de/rebranding <https://www.hereon.de/rebranding>

------------------------------------------------------------------------------
Helmholtz-Zentrum hereon GmbH
Max-Planck-Straße 1 I 21502 Geesthacht I Deutschland/Germany

Geschäftsführung I Board of Management: Prof. Dr. Matthias Rehahn, Silke Simon
Vorsitzender des Aufsichtsrates I Chairman of the Supervisory Board: Ministerialdirigent Engelbert Beyer
Amtsgericht Lübeck HRB 285 GE (Register Court)
Internet: www.hereon.de <https://www.hereon.de>

**Comment by richardreeve** [comment]
Ah, thank you. I presume you're talking about this:

> The normalized beta diversity index (denoted rho bar) measures representativeness and assesses how well a SC represents the species composition of MC. It is maximized (1) when the MC is homogenous, ...

If so, this is slightly confusing I now realise (for which apologies), but not a mistake. There are two different types of beta diversity measures, beta and rho - the one being referred to here is normalised rho (`norm_rho()`), which measures representativeness - unlike raw beta, which measures distinctiveness that I mentioned earlier.
